---
- name: Reread supervisor
  community.general.supervisorctl:
    name: all
    state: present
  listen: "Reread supervisor"

- name: Update supervisor
  ansible.builtin.command: supervisorctl update
  changed_when: false
  listen: "Update supervisor"
