---
- name: Reread supervisor
  ansible.builtin.command: supervisorctl reread
  changed_when: false
  listen: "Reread supervisor"

- name: Update supervisor
  ansible.builtin.command: supervisorctl update
  changed_when: false
  listen: "Update supervisor"
