---
- name: Create app database
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ app_name }}"
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    state: present

- name: Create app MySQL user
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ app_name }}"
    host: localhost
    password: "{{ db_pass }}"
    priv: "{{ app_name }}.*:ALL"
    state: present
  no_log: true
